---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "man/figures/README-",
  out.width = "100%"
)
```

# topicl

<!-- badges: start -->
<!-- badges: end -->

The goal of topicl is to provide tools for identifying stable
(reproducible) topics and for their analysis.

## Installation

You can install the development version of topicl from
[GitHub](https://github.com/) with:

``` r
# install.packages("pak")
pak::pak("paskn/topicl")
```

## Example

This is a basic example which shows you how to solve a common problem:

```{r example, message=FALSE, warning=FALSE}
library(topicl)
library(stm)
library(dplyr)

modA <- stm(poliblog5k.docs, 
            poliblog5k.voc, K=25,
            prevalence=~rating, 
            data=poliblog5k.meta,
            max.em.its=2, 
            init.type="Random",
            seed = 9934,
            verbose = F) 
           
modB <- stm(poliblog5k.docs, 
            poliblog5k.voc, K=25,
            prevalence=~rating, 
            data=poliblog5k.meta,
            max.em.its=2, 
            init.type="Random",
            seed = 9576,
            verbose = F) 
           
compare_solutions(list(modA, modB), depth=500) |> 
  arrange(desc(jaccard)) |> 
  head()

```

